### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by dongdongbh** [kltk/v2ray-tools#13]
```
TypeError: Cannot read properties of undefined (reading 'split')
    at createVmessObj (/usr/local/lib/node_modules/v2ray-tools/src/config2vmess.js:50:46)
    at createEncodedUrl (/usr/local/lib/node_modules/v2ray-tools/src/config2vmess.js:78:22)
    at config2vmess (/usr/local/lib/node_modules/v2ray-tools/src/config2vmess.js:90:21)
    at Object.config2VmessHandler [as handler] (/usr/local/lib/node_modules/v2ray-tools/src/cli.js:41:20)
    at Object.runCommand (/usr/local/lib/node_modules/v2ray-tools/node_modules/yargs/lib/command.js:240:40)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/v2ray-tools/node_modules/yargs/yargs.js:1105:41)
    at Object.get [as argv] (/usr/local/lib/node_modules/v2ray-tools/node_modules/yargs/yargs.js:1033:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/v2ray-tools/src/cli.js:77:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
false
```

**Comment by tarborali** [comment]
I guess adding a "tag" property to the first outbound object would fix the problem
replace `ps`, `add` and `port` with their value
...
outbounds: [{
  "tag": "[ps] [add] [port]"
   ...

**Comment by AliSawari** [comment]
@dongdongbh 
a fix is available at #18. This is a duplicate of  #15 . or the vice versa actually because this one was opened first, my bad :)
in any case, this also should be close once #18 gets merged.
