### ISSUE TITLE
Error while converting config to url

### ISSUE THREAD

**Issue by deadmann** [kltk/v2ray-tools#15]
```
C:\v2ray-windows-64>v2ray-tools config2vmess --path="C:\v2ray-windows-64\clientConfig.json"
TypeError: Cannot read property 'split' of undefined
    at createVmessObj (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\src\config2vmess.js:51:34)
    at createEncodedUrl (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\src\config2vmess.js:85:22)
    at config2vmess (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\src\config2vmess.js:97:21)
    at Object.config2VmessHandler [as handler] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\src\cli.js:41:20)
    at Object.runCommand (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\node_modules\yargs\lib\command.js:240:40)
    at Object.parseArgs [as _parseArgs] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\node_modules\yargs\yargs.js:1105:41)
    at Object.get [as argv] (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\node_modules\yargs\yargs.js:1033:21)
    at Object.<anonymous> (C:\Users\Administrator\AppData\Roaming\npm\node_modules\v2ray-tools\src\cli.js:77:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
false

C:\v2ray-windows-64>
```

Note it is also unable to process `//` comments white become common in some applications (those applications tend to remove comment and then process the file.

```
{
  "inbounds": [{
    "port": <XXXX>,
    "listen": "127.0.0.1",
    "protocol": "socks",
    "settings": {
      "udp": true
    }
  }],
  "outbounds": [{
    "protocol": "vmess",
    "settings": {
      "vnext": [{
        "address": "<IP V4>",
        "port": <XXXXX>,
        "users": [{ "id": "<A GUID VALUE>" }]
      }]
    }
  },{
    "protocol": "freedom",
    "tag": "direct",
    "settings": {}
  }],
  "routing": {
    "domainStrategy": "IPOnDemand",
    "rules": [{
      "type": "field",
      "ip": ["geoip:private"],
      "outboundTag": "direct"
    }]
  }
}
```

**Comment by AliSawari** [comment]
@deadmann Thank you for reporing this issue. I have created a PR for this. #18 

 > Note it is also unable to process // comments white become common in some applications (those applications tend to remove comment and then process the file.

I don't think comments are a standard in JSON. also I haven't seen any Xray/V2ray panel or app generate Config JSON files with comments. would you please reference one ? that would be helpful :)  

I can find  the regex one-liner that removes the comments, but im not sure  if its in the scope of this tool

P.S , it seems like this issue is mostly a duplicate of #13
